<definition>
	<command name="click">
		<case locator1="locator1">
			<execute function="Click#clickAt" />
		</case>
	</command>

	<command name="click">
		<case locator1="locator1">
			<execute function="Click#clickAt" />
		</case>
	</command>
</definition>